wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.7
    cli_version: 0.16.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1704794006.702427
    t:
      1:
      - 1
      - 50
      - 55
      - 105
      3:
      - 23
      4: 3.11.7
      5: 0.16.1
      8:
      - 5
      13: darwin-arm64
