# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace         # Trims trailing whitespace
    -   id: end-of-file-fixer           # Ensures that a file is either empty, or ends with one newline
    -   id: check-yaml                  # Checks yaml files are valid, and for parseable syntax
    -   id: check-added-large-files     # Checks for large files being added to git, and prevents giant files from being committed

#-   repo: https://github.com/astral-sh/ruff-pre-commit
#    rev: v0.1.11                          # Ruff version.
#    hooks:
#    -   id: ruff                          # Run the linter
#    -   id: ruff-format                   # Run the formatter.
